export { default as FeedBackComponent } from './feedBack'
export { default as QuizComponent } from './quiz'
export { default as SettingsComponent } from './settings'
export { default as TelethonComponent } from './telethon'
export { default as AuthenticationComponent } from './authentication'
export { default as MainPageBanners } from './mainPageBanner'
export { default as Buttons } from './buttons'
export { default as Logoline } from './logoLine'
export { default as HomePopUp } from './homePopUp'
export { default as App_Version_Error } from './appVersionError'
export { HeaderDivComp } from './headerDivComp'
export { RenderWebViewComponent, RenderHTMLComponent } from './webViewAndRenderHTML'