export { default as AboutComponent } from './about'
export { default as ContactUsComponent } from './contactUs'
export { default as DonateComponent } from './donate'
export { default as DownloadsComponent } from './downloads'
export { default as FeedBackComponent } from './feedBack'
export { default as GraveSearchComponent } from './graveSearch'
export { default as HomeComponent } from './home'
export { default as NewsEventsComponent } from './newsEvents'
export { default as ObituaryComponent } from './obituary'
export { default as QuizComponent } from './quiz'
export { default as SettingsComponent } from './settings'
export { default as TelethonComponent } from './telethon'
export { default as AuthenticationComponent } from './authentication'
export { default as MainPageBanners } from './mainPageBanner'
export { default as Buttons } from './buttons'
export { default as Logoline } from './logoLine'
export { default as HomePopUp } from './homePopUp'
export { HeaderDivComp } from './headerDivComp'