export const types = {
  AUTH_START: "AUTH_START",
  AUTH_SUCCESS: "AUTH_SUCCESS",
  AUTH_FAILD: "AUTH_FAILD",
  SING_OUT: "SING_OUT",

  FETCH_USER_START: "FETCH_USER_START",
  FETCH_USER_SUCCESS: "FETCH_USER_SUCCESS",
  FETCH_USER_FAILED: "FETCH_USER_FAILED",

  SHOW_TOAST: "SHOW_TOAST",
  HIDE_TOAST: "HIDE_TOAST",

  APP_VERSION: "APP_VERSION",
  ALL_FLAGS: "ALL_FLAGS",
  FEMALE_DUMMY_IMAGE: "FEMALE_DUMMY_IMAGE",
  ABOUT_US: "ABOUT_US",
  DONATE_US: "DONATE_US",
  MAIN_PAGE_BANNERS: "MAIN_PAGE_BANNERS",
  POPUP_UPDATED: "POPUP_UPDATED",
  APP_OPENING_DATE: "APP_OPENING_DATE",

  DEATH_NEWS: "DEATH_NEWS",
  EVENT_NEWS: "EVENT_NEWS",

  SEND_FEEDBACK_START: "SEND_FEEDBACK_START",
  SEND_FEEDBACK_SUCCESS: "SEND_FEEDBACK_SUCCESS",
  SEND_FEEDBACK_FAILED: "SEND_FEEDBACK_FAILED",

  AUTH_VERIFY_START: "AUTH_VERIFY_START",
  AUTH_VERIFY_SUCCESS: "AUTH_VERIFY_SUCCESS",
  AUTH_VERIFY_FAILD: "AUTH_VERIFY_FAILD",

  USER_LOGIN_SUCCESSFULLY: "USER_LOGIN_SUCCESSFULLY",
  USER_LOGIN_FAILED: "USER_LOGIN_FAILED",

  USER_DATA_REMOVED: "USER_DATA_REMOVED"
};
